auth:
  existingSecret: pg-credentials
  secretKeys:
    adminPasswordKey: postgres-password
    userPasswordKey: password
  username: appuser
  database: appdb
primary:
  persistence:
    enabled: true
    size: 2Gi
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
