apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: git-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: git-creds
    creationPolicy: Merge
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: argocd/git-creds
        property: username
    - secretKey: password
      remoteRef:
        key: argocd/git-creds
        property: password
