apiVersion: v1
kind: Pod
metadata:
  name: "sorcery-test-connection"
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  containers:
    - name: test-backend
      image: busybox
      command: ['wget', '-qO-', 'http://sorcery-app-staging-backend.staging.svc.cluster.local:8080/health']
  restartPolicy: Never
