namespace: staging
ingress:
  host: staging.gitops.local
frontend:
  replicaCount: 2
  image:
    tag: "1.27.9999-does-not-exist"
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 70
config:
  appEnvironment: "staging"
