namespace: app
backend:
  replicaCount: 1
  image:
    repository: hashicorp/http-echo
    tag: "1.0"
    pullPolicy: IfNotPresent
  port: 8080
  args:
  - "-listen=:8080"
  - "-text=Hello from the backend! Pod: $(POD_NAME)"
  env:
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi
frontend:
  replicaCount: 2
  image:
    repository: nginx
    tag: "1.27.9999-does-not-exist"
    pullPolicy: IfNotPresent
  port: 80
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
ingress:
  enabled: true
  host: gitops.local
config:
  appEnvironment: "ci-build-3"
