backend:
  replicaCount: 1
  image:
    repository: hashicorp/http-echo
    tag: "broken-does-not-exist"
    pullPolicy: IfNotPresent
  port: 8080
  args:
  - "-listen=:8080"
  - "-text=Hello from the backend! Pod: $(POD_NAME)"
  env:
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi
frontend:
  image:
    repository: nginx
    tag: "1.27.5"
    pullPolicy: IfNotPresent
  port: 80
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi
ingress:
  enabled: true
config:
  lastCIBuild: "14"
